### ISSUE TITLE
Console Spam on Latest MMOCore

### ISSUE THREAD

**Issue by MusicTW** [mmopluginteam/mmocore#127]
Please include a latest.log uploaded to pastebin.com here:
https://pastebin.com/DeTmK9jJ

Describe the bug
Console Spam. Occurs randomly and spams constantly.

Server info:

Paper 1.16.1 #108
MMOLib 1.2.6 / MMOCore 1.4.2-SNAPSHOT / MMOItems 5.5.3

**Comment by ASangarin** [comment]
The error does not provide enough information. Please provide a latest log

**Comment by pixelsquared** [comment]
**Please include a `latest.log` uploaded to [pastebin.com](https://pastebin.com) here:**
https://pastebin.com/gcNdwCMR

**Describe the bug**
Spams the server console with tons of messages.

**To Reproduce**
Steps to reproduce the behavior:
1. Download paper 1.16.1 server
2. Add MMOCore and MMOLib to plugin folder
3. Watch console for tons of messages

**Expected behavior**
Not Spamming the console with tons of messages.

**Screenshots**
N/A

**Server info:**
 - Spigot Build & Version: Paper version git-Paper-130 (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
 - Plugin Version: MMOCore-1.4.2
 - Potential plugins linked to the issue: None that I know of

**Additional context**
Add any other context about the problem here.

**Comment by Grumblin** [comment]
Pixelsquared's issue has been solved by updating to the latest builds of all of the mmo plugins.

@MusicTW please send your latest.log; though the issue can probably be solved by updating your plugins to the latest dev builds.

**Comment by MusicTW** [comment]
U mean this?
https://hastebin.com/eponicerof.rb

**Comment by jacobmepstein** [comment]
Yes -- update to the latest dev builds of all plugins. This should solve the problems.
