### ISSUE TITLE
Bug - Reverting back to vanilla HP amount, rather than the MMOCore set one on relog.

### ISSUE THREAD

**Issue by dexasz** [mmopluginteam/mmocore#23]
I've basically explained the issue in the name, help would be appreciated!

**Comment by Indyuce** [comment]
DIdn't manage to reproduce the issue on the latest dev build of MMOCore. I have tried relogging after disconnecting/restarting the server, using YAML and SQL data support which I thought might be the issue at first but apparently isn't (at least on my end). This issue needs further investigation.

**Comment by dexasz** [comment]
> DIdn't manage to reproduce the issue on the latest dev build of MMOCore. I have tried relogging after disconnecting/restarting the server, using YAML and SQL data support which I thought might be the issue at first but apparently isn't (at least on my end). This issue needs further investigation.

Maybe needs more investigating.. for example, if you have 30/30HP, on relog, you have 20/20 (why?); you switch to another item in your inventory, and attributes fix themselves, back to maximum of 30hp, but it doesn't heal back instantly, so you have to eat food again, etc.. so imagine you leveled your health to maximum of 100, on relog you now have 20/100 on item switch, so you wait again to feed up, heal once again..

**Comment by Indyuce** [comment]
I tried relogging with a +20 Max HP MMOItems helmet and with 26 base HP due to a MMOCore class, I still have 46 HP on relog.

**Comment by Indyuce** [comment]
That might be able to help: using MMOItems (MMOCore does not seem to affect the outcome) when logging back on the server with max health different from the vanilla value, the health bar is visually stuck onto 20HP whereas MMOCore placeholders indicate the player's health is still 124.

Even when using /heal the health bar stays stuck. The issue seems to fix itself sometimes, perhaps because of MMOCore regen runnables.
![image](https://user-images.githubusercontent.com/29358517/79635676-883a5300-8172-11ea-9687-bead6ea01bd4.png)

**Comment by AshenGaming** [comment]
Hi there! We're in the process of cleaning up the Github for MMOCore, and as such closing old issues. If you are still experiencing this issue, please open a new issue using the Issue Template format provided as opposed to re-opening this one.
