### ISSUE TITLE
Some things I can't understand

### ISSUE THREAD

**Issue by Nicotolew** [mmopluginteam/mmocore#39]
I am new to MMoCore and I have some doubts, they are not bugs, but things that I do not understand.

1- The skill points and attribute points I do not get when leveling up.

2- The damage of the Mithic mobs has no effect on my player when I use MMOCORE. (It deals the damage of vanilla default).

3- When I press F to load a skill, MANA and HEALT disappear from the screen and nothing else appears.

4- Can the player start with class points? So you can choose a class when you enter the game.

I know there are many questions but if you could help me, I appreciate it!

**Comment by Indyuce** [comment]
I'll start with the easy ones

4- Run a command when players join the server for the first time, or make them do a tutorial by the end of which they get their first class point: `/mmocore admin class-points give <player> <amount>`

3 and 2- these are probably issues, please be more specific on how to reproduce that issue, paste potential relevant console logs or config files, etc.

1- you can setup classes so that they give the player X attribute/skill points when leveling up. That would probably be a config issue. Most config loading issues are printed on the console so you might check your logs for MMOCore loading issues
