### ISSUE TITLE
[BUG] Guild accept does not work

### ISSUE THREAD

**Issue by soundless32** [mmopluginteam/mmocore#72]
Error: https://pastebin.com/QT2QdPbR
Error occures when invited player hits accept button

**Comment by Indyuce** [comment]
Have you tried resetting your messages.yml file? It looks like MMOCore cannot find the corresponding message translation in your local messages config file, it's either because the plugin didn't load correctly (double check your startup logs) or because you are missing some message. Based on the logs you sent, you might be missing `guild-joined-other`
